"use client";

import { useEffect, useMemo, useState } from "react";
import { FiBarChart2, FiRefreshCw } from "react-icons/fi";

const headers = () => ({ Authorization: `Bearer ${localStorage.getItem("token") || ""}` });
const fieldName = (column, index) => typeof column === "string" ? column.split(":")[0] : column?.fieldname || column?.label || `column_${index}`;
const fieldLabel = (column, index) => typeof column === "string" ? column.split(":")[0] : column?.label || column?.fieldname || `Column ${index + 1}`;

export default function WmsReportsPage() {
  const [reports, setReports] = useState([]), [selected, setSelected] = useState(""), [loading, setLoading] = useState(true), [running, setRunning] = useState(false), [result, setResult] = useState(null), [error, setError] = useState("");
  const selectedReport = useMemo(() => reports.find((report) => (report.report_name || report.name) === selected), [reports, selected]);
  async function loadReports() {
    try { setLoading(true); setError(""); const response = await fetch("/api/wms/reports", { headers: headers() }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload.message || "Unable to load ERPNext reports."); setReports(payload.data || []); } catch (requestError) { setError(requestError.message || "Unable to load ERPNext reports."); } finally { setLoading(false); }
  }
  useEffect(() => { loadReports(); }, []);
  async function runReport(reportName = selected) {
    if (!reportName) return;
    try { setRunning(true); setError(""); setResult(null); const response = await fetch("/api/wms/reports", { method: "POST", headers: { "Content-Type": "application/json", ...headers() }, body: JSON.stringify({ reportName }) }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload.message || "ERPNext could not run this report. It may need report filters."); setResult(payload.data); } catch (requestError) { setError(requestError.message || "Unable to run ERPNext report."); } finally { setRunning(false); }
  }
  const columns = result?.columns || [];
  return <div className="space-y-6"><section className="relative overflow-hidden rounded-3xl bg-gradient-to-br from-slate-950 via-slate-900 to-cyan-950 p-6 text-white shadow-xl md:p-8"><div className="absolute -right-16 -top-16 h-56 w-56 rounded-full bg-cyan-400/20 blur-3xl" /><div className="relative"><p className="text-xs font-bold uppercase tracking-[0.2em] text-cyan-300">Live ERPNext data</p><h1 className="mt-2 text-3xl font-bold">Reports</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-300">Select an ERPNext warehouse report and it opens immediately. Report data stays in ERPNext.</p></div></section>
    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm md:p-7"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-cyan-50 text-cyan-700"><FiBarChart2 size={21} /></span><div><h2 className="font-bold text-slate-900">ERPNext standard reports</h2><p className="text-sm text-slate-500">{loading ? "Loading reports..." : `${reports.length} warehouse reports available`}</p></div></div><div className="mt-6 grid gap-4 md:grid-cols-[minmax(0,1fr)_auto]"><label className="grid gap-2 text-sm font-semibold text-slate-700">Select report<select value={selected} onChange={(event) => { const reportName = event.target.value; setSelected(reportName); setResult(null); runReport(reportName); }} disabled={loading || running} className="rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm outline-none focus:border-cyan-500"><option value="">Choose an ERPNext report</option>{reports.map((report) => { const name = report.report_name || report.name; return <option key={name} value={name}>{name}{report.ref_doctype ? ` · ${report.ref_doctype}` : ""}</option>; })}</select></label><button type="button" onClick={loadReports} disabled={loading || running} className="self-end inline-flex items-center justify-center gap-2 rounded-xl border border-slate-300 px-4 py-2.5 text-sm font-bold text-slate-700 disabled:opacity-50"><FiRefreshCw className={loading ? "animate-spin" : ""} />Refresh</button></div>{running ? <p className="mt-4 text-sm font-semibold text-cyan-700">Opening ERPNext report...</p> : null}{selectedReport ? <p className="mt-4 rounded-xl bg-slate-50 px-4 py-3 text-sm text-slate-600">Selected: <strong>{selected}</strong>{selectedReport.ref_doctype ? ` · ERPNext document: ${selectedReport.ref_doctype}` : ""}</p> : null}</section>
    {error ? <div className="rounded-2xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">{error}</div> : null}
    {result ? <section className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 p-5"><h2 className="font-bold text-slate-900">{selected}</h2><p className="mt-1 text-sm text-slate-500">{result.rows?.length || 0} rows returned from ERPNext</p></div><div className="max-h-[520px] overflow-auto"><table className="min-w-full divide-y divide-slate-100"><thead className="sticky top-0 bg-slate-50"><tr>{columns.map((column, index) => <th key={fieldName(column, index)} className="whitespace-nowrap px-4 py-3 text-left text-[11px] font-bold uppercase tracking-wide text-slate-500">{fieldLabel(column, index)}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{(result.rows || []).map((row, rowIndex) => <tr key={rowIndex} className="hover:bg-slate-50">{columns.map((column, index) => { const key = fieldName(column, index); const value = Array.isArray(row) ? row[index] : row?.[key]; return <td key={key} className="whitespace-nowrap px-4 py-3 text-sm text-slate-700">{value ?? "-"}</td>; })}</tr>)}</tbody></table></div>{!result.rows?.length ? <p className="p-8 text-center text-sm text-slate-500">ERPNext returned no rows for this report.</p> : null}</section> : null}
  </div>;
}
