"use client";

import { useState } from "react";
import Link from "next/link";

export default function LocalWmsBulkImport() {
  const [file, setFile] = useState(null), [message, setMessage] = useState(""), [loading, setLoading] = useState(false);
  const upload = async (event) => { event.preventDefault(); if (!file) return; try { setLoading(true); const form = new FormData(); form.append("file", file); const response = await fetch("/api/wms/demo/bulk-import", { method: "POST", headers: { Authorization: `Bearer ${localStorage.getItem("token") || ""}` }, body: form }); const payload = await response.json(); setMessage(payload.message || ""); } catch { setMessage("Bulk import failed."); } finally { setLoading(false); } };
  return <div className="space-y-6"><section className="rounded-3xl bg-slate-950 p-7 text-white"><p className="text-xs font-bold uppercase tracking-[.2em] text-cyan-300">Warehouse Data Management</p><h1 className="mt-2 text-3xl font-bold">Bulk Data Import</h1><p className="mt-2 text-sm text-slate-300">Upload one Excel workbook to create racks, shelves, bins, and item-to-bin assignments together.</p></section><div className="flex gap-3 text-sm font-semibold"><Link href="/wms/locations" className="text-cyan-700">Control Center</Link><span>/</span><span>Bulk Data Import</span></div><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="font-bold">1. Use the bulk Excel template</h2><p className="mt-1 text-sm text-slate-500">Use the supplied <b>.xlsx</b> workbook. Every row is handled in one import: warehouse, rack, shelf, bin, and optional item assignment.</p><p className="mt-3 rounded-xl bg-slate-50 p-3 text-xs text-slate-600">Required columns: warehouseCode, state, rackCode, rackName, rackCapacity, shelfCode, shelfCapacity, binNumber, binCapacity, itemCode, itemName.</p><form onSubmit={upload} className="mt-7 border-t border-slate-100 pt-6"><h2 className="font-bold">2. Upload completed workbook</h2><input required accept=".xlsx,.xls,.csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.ms-excel,text/csv" type="file" onChange={(e) => setFile(e.target.files?.[0] || null)} className="mt-4 block w-full rounded-xl border border-slate-300 p-3 text-sm" /><button disabled={!file || loading} className="mt-4 rounded-xl bg-slate-950 px-5 py-2.5 text-sm font-bold text-white disabled:opacity-50">{loading ? "Importing..." : "Import All Data"}</button></form>{message ? <p className="mt-5 rounded-xl bg-cyan-50 p-4 text-sm text-cyan-900">{message}</p> : null}</section><section className="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm text-amber-900">This import creates warehouse location records, item assignments, and barcode-ready data. It does not modify ERPNext stock, warehouses, or items.</section></div>;
}
