"use client";

import { useEffect, useState } from "react";
import Link from "next/link";

const headers = () => ({ "Content-Type": "application/json", Authorization: `Bearer ${localStorage.getItem("token") || ""}` });

export default function LocalWmsShelves() {
  const [racks, setRacks] = useState([]), [shelves, setShelves] = useState([]), [form, setForm] = useState({ shelfCode: "", rackId: "", capacity: "" }), [message, setMessage] = useState("");
  const load = async () => { const [rackResponse, shelfResponse] = await Promise.all([fetch("/api/wms/demo/racks", { headers: headers() }), fetch("/api/wms/demo/shelves", { headers: headers() })]); const rackPayload = await rackResponse.json(), shelfPayload = await shelfResponse.json(); if (rackResponse.ok) setRacks(rackPayload.data || []); if (shelfResponse.ok) setShelves(shelfPayload.data || []); else setMessage(shelfPayload.message); };
  useEffect(() => { load(); }, []);
  const save = async (event) => { event.preventDefault(); const response = await fetch("/api/wms/demo/shelves", { method: "POST", headers: headers(), body: JSON.stringify(form) }); const payload = await response.json(); setMessage(payload.message || ""); if (response.ok) { setForm({ shelfCode: "", rackId: "", capacity: "" }); load(); } };
  return <div className="space-y-6"><section className="rounded-3xl bg-slate-950 p-7 text-white"><p className="text-xs font-bold uppercase tracking-[.2em] text-cyan-300">Warehouse Location Masters</p><h1 className="mt-2 text-3xl font-bold">Shelves</h1><p className="mt-2 text-sm text-slate-300">Each shelf belongs to one rack. Create a rack first, then add shelves below it.</p></section><div className="flex gap-3 text-sm font-semibold"><Link href="/wms/locations" className="text-cyan-700">Control Center</Link><span>/</span><Link href="/wms/locations/racks" className="text-cyan-700">Racks</Link><span>/</span><span>Shelves</span><Link href="/wms/locations/bin-locations" className="ml-auto text-cyan-700">Open Bin Master →</Link></div>{message ? <p className="rounded-xl bg-slate-100 p-3 text-sm">{message}</p> : null}<section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold">Create Shelf</h2><form onSubmit={save} className="mt-4 grid gap-3 md:grid-cols-4"><input required placeholder="Shelf code (S01)" value={form.shelfCode} onChange={(e) => setForm({ ...form, shelfCode: e.target.value })} className="rounded-xl border border-slate-300 px-3 py-2.5" /><select required value={form.rackId} onChange={(e) => setForm({ ...form, rackId: e.target.value })} className="rounded-xl border border-slate-300 px-3 py-2.5"><option value="">Select rack</option>{racks.map((rack) => <option key={rack._id} value={rack._id}>{rack.rackCode} - {rack.name}</option>)}</select><input type="number" min="0" placeholder="Capacity" value={form.capacity} onChange={(e) => setForm({ ...form, capacity: e.target.value })} className="rounded-xl border border-slate-300 px-3 py-2.5" /><button disabled={!racks.length} className="rounded-xl bg-slate-950 px-4 py-2.5 font-bold text-white disabled:opacity-50">Save Shelf</button></form>{!racks.length ? <p className="mt-3 text-sm text-amber-700">Create a Rack first.</p> : null}</section><section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left"><tr><th className="p-3">Shelf Code</th><th className="p-3">Rack</th><th className="p-3">Capacity</th><th className="p-3">Status</th></tr></thead><tbody>{shelves.map((shelf) => <tr key={shelf._id} className="border-t"><td className="p-3 font-semibold">{shelf.shelfCode}</td><td className="p-3">{shelf.rackId?.rackCode || "-"}</td><td className="p-3">{shelf.capacity}</td><td className="p-3">{shelf.status}</td></tr>)}{!shelves.length ? <tr><td colSpan="4" className="p-8 text-center text-slate-500">No shelves created yet.</td></tr> : null}</tbody></table></section></div>;
}
