"use client";

import { useEffect, useState } from "react";
import Link from "next/link";

const headers = () => ({ "Content-Type": "application/json", Authorization: `Bearer ${localStorage.getItem("token") || ""}` });

export default function LocalWmsRacks() {
  const [racks, setRacks] = useState([]), [form, setForm] = useState({ rackCode: "", name: "", capacity: "" }), [message, setMessage] = useState("");
  const load = async () => { const response = await fetch("/api/wms/demo/racks", { headers: headers() }); const payload = await response.json(); if (response.ok) setRacks(payload.data || []); else setMessage(payload.message); };
  useEffect(() => { load(); }, []);
  const save = async (event) => { event.preventDefault(); const response = await fetch("/api/wms/demo/racks", { method: "POST", headers: headers(), body: JSON.stringify(form) }); const payload = await response.json(); setMessage(payload.message || ""); if (response.ok) { setForm({ rackCode: "", name: "", capacity: "" }); load(); } };
  return <div className="space-y-6"><section className="rounded-3xl bg-slate-950 p-7 text-white"><p className="text-xs font-bold uppercase tracking-[.2em] text-cyan-300">Warehouse Location Masters</p><h1 className="mt-2 text-3xl font-bold">Racks</h1><p className="mt-2 text-sm text-slate-300">Build the location hierarchy: Rack → Shelf → Bin Location.</p></section><div className="flex gap-3 text-sm font-semibold"><Link href="/wms/locations" className="text-cyan-700">Control Center</Link><span>/</span><span>Racks</span><Link href="/wms/locations/shelves" className="ml-auto text-cyan-700">Open Shelf Master →</Link></div>{message ? <p className="rounded-xl bg-slate-100 p-3 text-sm">{message}</p> : null}<section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold">Create Rack</h2><form onSubmit={save} className="mt-4 grid gap-3 md:grid-cols-4"><input required placeholder="Rack code (R01)" value={form.rackCode} onChange={(e) => setForm({ ...form, rackCode: e.target.value })} className="rounded-xl border border-slate-300 px-3 py-2.5" /><input required placeholder="Rack name" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} className="rounded-xl border border-slate-300 px-3 py-2.5" /><input type="number" min="0" placeholder="Capacity" value={form.capacity} onChange={(e) => setForm({ ...form, capacity: e.target.value })} className="rounded-xl border border-slate-300 px-3 py-2.5" /><button className="rounded-xl bg-slate-950 px-4 py-2.5 font-bold text-white">Save Rack</button></form></section><section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left"><tr><th className="p-3">Code</th><th className="p-3">Name</th><th className="p-3">Capacity</th><th className="p-3">Status</th></tr></thead><tbody>{racks.map((rack) => <tr key={rack._id} className="border-t"><td className="p-3 font-semibold">{rack.rackCode}</td><td className="p-3">{rack.name}</td><td className="p-3">{rack.capacity}</td><td className="p-3">{rack.status}</td></tr>)}{!racks.length ? <tr><td colSpan="4" className="p-8 text-center text-slate-500">No racks created yet.</td></tr> : null}</tbody></table></section></div>;
}
